### ISSUE TITLE
skip_locked with MariaDB

### ISSUE THREAD

**Issue by b3ni** [idlesign/django-sitemessage#11]
The option skip_locked for select_for_update fails in MariaDB backend.

https://github.com/idlesign/django-sitemessage/blob/master/sitemessage/models.py

django.db.utils.NotSupportedError: SKIP LOCKED is not supported on this database backend.

**Comment by idlesign** [comment]
Thank you for the report.

I guess we need a better heuristic than the current one to resolve db features
https://github.com/idlesign/django-sitemessage/blob/master/sitemessage/models.py#L308

Can you check whether ``no_wait`` is supported?

**Comment by b3ni** [comment]
The nowait option also fails.

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOWAIT' at line 1

Im using mariadb:10.1.34

select_for_update_kwargs = {} 
It works but I'm not sure that's right

**Comment by idlesign** [comment]
Ok, thank you. 

I'll try to make a workaround for MariaDB this or the following week. 
But you should bear in mind that it won't be distributed-friendly on MariaDB (so you souldn't run send scheduled on more that project instance simultaneously if they wotk with the same DB).
