### ISSUE TITLE
This seems like a good project, but why are there no issues?

### ISSUE THREAD

**Issue by gabn88** [idlesign/django-sitemessage#2]
I would like to use this module in a production site, is it safe?

**Comment by idlesign** [comment]
For the given value of safe.

Consider this:
1. version number is < 1.0;
2. 826 fetches from PyPI this month;
3. for other aspecs of fitness please refer LICENSE file.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
